// Cerita deklaratif: aturan perubahan state berada di engine.mjs.
const choice = (id, label, result, effects = {}, extra = {}) => ({ id, label, result, effects, ...extra });
export const EVENTS = [
  {
    id: 'first-seat', chapter: 0, scene: 'classroom', speaker: 'Tio', title: 'Satu kursi kosong',
    text: 'Pagi pertama kelas 10. Kamu berdiri di pintu dengan jadwal pelajaran yang sudah sedikit kusut. Semua orang tampak sudah punya teman, padahal mungkin mereka sama gugupnya. Tio melambaikan tangan dari baris belakang. Di dekat jendela, Maya sedang merapikan buku dan menunjuk kursi kosong di sebelahnya.\n\nSaat istirahat, Tio mengajakmu bergabung dengan kelompoknya. Obrolan mereka ramai sampai seseorang menirukan cara bicara seorang teman yang duduk sendirian. Beberapa orang tertawa. Kamu belum mengenal siapa pun cukup dekat untuk tahu apakah ini candaan yang diterima semua orang. Teman itu menunduk dan beranjak pergi. Tio menoleh kepadamu, menunggu reaksimu.',
    quote: 'Duduk bareng kita aja. Santai, di sini orangnya seru-seru.',
    lesson: 'Rasa ingin diterima itu wajar. Kamu tetap bisa membangun pertemanan tanpa ikut mempermalukan orang lain.',
    choices: [
      choice('speak', 'Bilang candaan itu kelewatan, lalu ajak teman tadi duduk bersama.', 'Suasana sempat hening. Tio menggaruk kepala dan menggeser kursi. Tidak semua orang langsung setuju denganmu, tetapi teman itu kembali duduk. Kamu pulang dengan sedikit gugup sekaligus lega: setidaknya orang mulai tahu batas candaan yang bisa kamu terima.', { confidence: 9, mood: 3 }, { relations: { friend: 3, peer: 5 }, flags: { stoodUp: true } }),
      choice('private', 'Susul teman itu, lalu bicarakan candaan tadi dengan Tio secara pribadi.', 'Teman itu mengaku tidak nyaman. Kamu mendengarkan, kemudian menyampaikan ke Tio tanpa mempermalukannya di depan kelompok. Tio awalnya defensif, tetapi akhirnya mengangguk. Menjaga suasana tidak harus berarti membiarkan semuanya lewat begitu saja.', { confidence: 5, energy: -3 }, { relations: { friend: 6 }, flags: { stoodUp: true } }),
      choice('silent', 'Tetap bersama kelompok dan tidak ikut menanggapi.', 'Obrolan berpindah topik dan kamu diterima di meja itu. Namun, saat bertemu teman tadi di lorong, kalian hanya saling melirik. Kamu belum siap bicara hari ini. Kesempatan untuk bersikap berbeda masih ada pada pertemuan berikutnya.', { mood: -5 }, { relations: { friend: 3 } }),
    ],
  },
  {
    id: 'group-work', chapter: 0, scene: 'classroom', speaker: 'Maya', title: 'Nama di sampul tugas',
    text: 'Sebulan berlalu. Kamu, Tio, dan Maya mendapat tugas presentasi. Maya mengirim daftar pekerjaan, Tio menawarkan diri membuat ilustrasi, dan kamu menyiapkan penjelasan. Malam sebelum pengumpulan, bagian Tio masih kosong. Ia baru membalas setelah kamu mengirim pesan kedua: seharian ia membantu keluarganya dan sekarang bingung harus mulai dari mana.\n\nMaya mengusulkan menghapus nama Tio dari sampul. Kamu memahami kekesalannya, tetapi juga tahu Tio sedang kewalahan. Besok kalian tetap harus tampil. Mengambil semua pekerjaannya sendiri mungkin menyelamatkan presentasi, tetapi waktumu untuk memahami materi akan habis. Kalian perlu memutuskan apa yang masih adil dan mungkin dilakukan malam ini.',
    quote: 'Aku mau tugas kita selesai, tapi masa yang kerja selalu orang yang sama?',
    lesson: 'Pembagian kerja yang jelas dan komunikasi lebih awal membantu kelompok. Membantu bukan berarti harus mengambil semua tanggung jawab.',
    choices: [
      choice('divide', 'Bagi ulang tugas kecil dengan tenggat malam ini dan minta Tio memilih bagiannya.', 'Tio menyelesaikan dua ilustrasi sederhana. Maya memang harus mengurangi detail desain, tetapi semua orang punya kontribusi yang bisa dijelaskan. Presentasi kalian tidak paling megah. Saat guru bertanya, kalian justru bisa menjawab bergantian karena memahami bagian masing-masing.', { academic: 7, energy: -5, confidence: 4 }, { relations: { friend: 7, peer: 7 }, flags: { teamwork: true } }),
      choice('takeover', 'Kerjakan bagian yang kosong sendiri agar presentasinya aman.', 'Berkas selesai menjelang tengah malam. Maya berterima kasih dan Tio merasa bersalah. Kamu berhasil menutup kekurangan kelompok, tetapi pagi berikutnya sulit berkonsentrasi. Tio juga tidak sempat belajar mengerjakan bagiannya. Cara ini menyelesaikan tugas hari ini, bukan kebiasaan kelompok kalian.', { academic: 5, energy: -15, mood: -5 }, { relations: { peer: 3 } }),
      choice('teacher', 'Sampaikan kontribusi sebenarnya kepada guru dan minta arahan sebelum presentasi.', 'Guru meminta kalian menjelaskan situasinya tanpa saling menyerang, lalu memberi Tio pekerjaan susulan. Tio malu karena masalahnya dibahas, tetapi kamu tidak menyebarkan urusan keluarganya. Maya merasa kerja kalian dihargai. Hubungan dengan Tio perlu dibicarakan lagi setelah kelas.', { academic: 4, confidence: 7 }, { relations: { friend: -4, peer: 6 } }),
    ],
  },
  {
    id: 'first-score', chapter: 0, scene: 'bedroom', speaker: 'Maya', title: 'Angka merah pertama',
    text: 'Nilai ulanganmu jauh di bawah harapan. Di grup kelas, beberapa teman mengirim foto nilai tinggi. Kamu sudah belajar, jadi hasil ini terasa lebih menyebalkan daripada sekadar tidak siap. Saat memeriksa lembar jawaban, kamu melihat kesalahan yang berulang pada jenis soal yang sama.\n\nMaya menawarkan belajar bersama dua sore dalam seminggu. Tio mengingatkan bahwa kalian sudah berjanji berkumpul setelah sekolah. Kamu merasa seolah harus memilih antara punya teman dan punya nilai bagus. Padahal jadwal itu masih bisa dibicarakan. Malam ini kamu membuka buku, lalu menutupnya lagi. Kamu ingin membuktikan bahwa angka tadi bukan gambaran seluruh kemampuanmu.',
    quote: 'Kita bahas cara ngerjainnya aja. Nggak harus langsung ngerti semua malam ini.',
    lesson: 'Nilai memberi informasi tentang bagian yang perlu dipelajari. Mengubah strategi lebih berguna daripada sekadar menambah jam tanpa arah.',
    choices: [
      choice('routine', 'Pelajari kesalahan bersama Maya dan sisakan satu sore untuk teman.', 'Kamu menemukan konsep yang selama ini hanya dihafalkan. Tio sempat kecewa karena jadwal berubah, tetapi kalian menentukan hari lain. Perbaikan nilaimu tidak instan. Yang berubah lebih dulu adalah kamu tahu harus mulai dari mana ketika membuka buku.', { academic: 12, energy: -4, confidence: 5 }, { relations: { peer: 7 }, flags: { studyHabit: true } }),
      choice('cram', 'Batalkan kegiatan lain dan belajar sampai larut setiap malam minggu ini.', 'Beberapa soal mulai terasa familiar, tetapi menjelang akhir minggu kamu membaca paragraf yang sama berulang kali. Usahamu sungguh-sungguh, hanya saja jadwalnya sulit dipertahankan. Kamu kehilangan waktu untuk beristirahat dan mengobrol dengan orang yang biasanya membuatmu lebih ringan.', { academic: 7, energy: -17, mood: -7 }, { relations: { friend: -3 } }),
      choice('avoid', 'Simpan lembar nilai dan ikut berkumpul dulu agar pikiran lebih ringan.', 'Sore bersama teman membuatmu bisa tertawa lagi. Namun, saat pelajaran berikutnya dimulai, bagian yang belum dipahami tetap terasa asing. Istirahat memberimu ruang bernapas; setelah itu masih diperlukan langkah untuk mengejar materi yang tertinggal.', { mood: 9, energy: 5, academic: -6 }, { relations: { friend: 5 } }),
    ],
  },
  {
    id: 'closer', chapter: 0, scene: 'courtyard', speaker: 'close', title: 'Lebih dari teman?', milestone: true,
    text: 'Menjelang akhir kelas 10, kamu semakin sering pulang bersama {close}. Awalnya kalian hanya bertukar catatan. Sekarang kamu hafal cerita kecil tentang harinya, termasuk lagu yang diputar saat perjalanan pulang. Tio mulai menggoda setiap kali kalian terlihat bersama. Kamu ikut tertawa, meski sebenarnya belum tahu apa yang kamu inginkan.\n\nSore ini halaman sekolah hampir kosong. {close} bertanya apakah kedekatan kalian bisa menjadi sesuatu yang lebih. Tidak ada penonton, tidak ada desakan dari teman-teman. Kamu senang dipercaya, tetapi juga memikirkan waktu, pertemanan, dan kesiapanmu sendiri. Jawabanmu akan menentukan cara kalian melanjutkan hubungan, bukan menentukan seberapa berharganya salah satu dari kalian.',
    quote: 'Aku nyaman sama kamu. Tapi aku pengen tahu kamu ngerasain apa, bukan kata orang lain.',
    lesson: 'Hubungan perlu keinginan kedua pihak. Memilih berteman atau belum siap sama sahnya dengan memilih pacaran.',
    choices: [
      choice('date', 'Katakan kamu juga tertarik dan bicarakan batas waktu serta privasi sejak awal.', 'Kalian memilih mencoba pacaran. Pembicaraan awal terasa agak canggung, terutama saat menyebut waktu belajar dan ruang pribadi. Namun, kalian sepakat kedekatan tidak harus membuat seluruh kegiatan dilakukan berdua. Ini awal hubungan, bukan janji bahwa kalian tidak akan pernah berbeda pendapat.', { mood: 9, confidence: 5 }, { relations: { close: 10 }, flags: { bond: 'dating', boundaries: true } }),
      choice('friends', 'Jelaskan bahwa kamu ingin tetap berteman dan tidak memberi harapan yang berbeda.', '{close} membutuhkan waktu untuk mencerna jawabanmu. Kalian tidak langsung kembali bercanda seperti biasa, tetapi kamu memberi ruang tanpa menghilang. Beberapa hari kemudian, obrolan tentang tugas dimulai lagi. Hubungan kalian masih berarti meski tidak menjadi pacaran.', { confidence: 8, mood: -2 }, { relations: { close: 5 }, flags: { bond: 'friends', boundaries: true } }),
      choice('slow', 'Jujur bahwa kamu belum yakin dan minta tetap saling mengenal tanpa janji.', '{close} mengangguk, lalu meminta agar kalian tidak saling menuntut seperti pasangan. Kamu setuju. Belum memiliki jawaban bukan masalah selama kamu tidak membuat orang lain menunggu dengan janji yang tidak sungguh-sungguh. Kalian melanjutkan kedekatan dengan harapan yang lebih jelas.', { confidence: 5, mood: 4 }, { relations: { close: 5 }, flags: { bond: 'slow' } }),
    ],
  },
  {
    id: 'privacy', chapter: 1, scene: 'canteen', speaker: 'close', title: 'Boleh lihat chat-mu?', milestone: true,
    text: 'Kelas 11 membawa jadwal dan teman kelompok baru. Kamu sering berdiskusi dengan Maya tentang proyek kelas. Suatu siang di kantin, ponselmu menyala ketika pesan Maya masuk. {close} melihat sekilas, lalu bertanya kenapa kalian sering sekali bertukar pesan.\n\nKamu menjelaskan bahwa proyeknya belum selesai. Namun, {close} masih terlihat gelisah dan meminta membaca percakapan kalian agar merasa tenang. Di dalamnya ada juga cerita pribadi Maya yang tidak berkaitan dengan hubungan kalian. Kamu ingin meredakan suasana, tetapi menyerahkan ponsel berarti memberi akses pada cerita orang lain. Di meja sebelah, teman-teman sudah memanggil untuk kembali ke kelas. Kalian hanya punya beberapa menit untuk mulai membicarakannya.',
    variants: [{ when: { bond: 'friends' }, text: 'Sejak kalian sepakat berteman, {close} khawatir kehilangan kedekatan saat kamu makin sering belajar bersama Maya. Permintaan melihat chat muncul sebagai tuntutan pembuktian bahwa kalian masih sahabat.' }],
    quote: 'Kalau memang nggak ada apa-apa, kenapa aku nggak boleh lihat?',
    lesson: 'Kedekatan tidak memberi hak otomatis atas pesan atau sandi orang lain. Kekhawatiran bisa dibicarakan tanpa menghapus privasi.',
    choices: [
      choice('boundary', 'Tolak membuka chat, lalu tawarkan percakapan tentang apa yang membuatnya khawatir.', '{close} awalnya merasa ditolak. Kamu menjelaskan bahwa menjaga cerita Maya bukan berarti menyembunyikan hubungan. Kalian belum menyelesaikan semuanya sebelum bel masuk, tetapi sepakat bicara lagi sore ini. Kamu tidak harus mengorbankan privasi untuk mulai mendengarkan perasaan seseorang.', { confidence: 9, energy: -4 }, { relations: { close: 4, peer: 4 }, flags: { boundaries: true, sharedChat: false } }),
      choice('show', 'Perlihatkan percakapan supaya pertanyaan itu cepat selesai.', 'Suasana segera lebih tenang, tetapi cerita pribadi Maya ikut terbaca. Setelahnya kamu merasa kurang nyaman. Masalah kepercayaan belum sungguh-sungguh dibicarakan, dan sekarang ada harapan bahwa ponselmu bisa diperiksa lagi setiap kali muncul rasa khawatir.', { mood: -7, confidence: -6 }, { relations: { close: 2, peer: -9 }, flags: { sharedChat: true, boundaries: false } }),
      choice('pause', 'Hentikan percakapan saat nada mulai naik dan ajak bicara nanti di tempat lebih tenang.', 'Kamu menyimpan ponsel dan kembali ke kelas. Sore harinya kamu menghubungi {close}, menjelaskan bahwa kamu mau mendengar kekhawatirannya tanpa pemeriksaan chat. Jeda membuat kalian lebih siap mendengar, meski rasa tidak nyaman tidak hilang dalam satu percakapan.', { energy: 3, confidence: 6 }, { relations: { close: 2 }, flags: { boundaries: true, sharedChat: false } }),
    ],
  },
  {
    id: 'rumor', chapter: 1, scene: 'bedroom', speaker: 'Tio', title: 'Sudah tersebar',
    text: 'Sebuah tangkapan layar dari grup kecil beredar ke grup kelas. Pesan yang dipotong membuat Maya terlihat merendahkan teman-temannya. Kamu pernah membaca percakapan lengkapnya: ia sedang membahas tugas, bukan kemampuan orang lain. Tio meneruskan gambar itu kepadamu dan bertanya apakah isinya benar.\n\nMaya tidak masuk sekolah hari ini. Kamu ingin membelanya, tetapi mengunggah seluruh percakapan akan membuka bagian pribadi yang juga tidak seharusnya disebar. Beberapa teman sudah membuat lelucon. Ponselmu terus bergetar, seolah setiap menit tanpa jawaban berarti kamu harus segera memilih pihak. Kamu bisa memperlambat penyebaran, menghubungi Maya, atau ikut menambah keramaian.',
    variants: [{ when: { sharedChat: true }, text: 'Kamu teringat pernah memperlihatkan chat Maya tanpa izinnya. Kamu tidak tahu apakah itu terkait dengan gambar yang beredar, jadi kamu tidak menuduh siapa pun. Namun, kamu perlu jujur kepada Maya tentang tindakanmu sendiri.' }],
    quote: 'Ini bener Maya ngomong begini? Gue belum terusin ke yang lain.',
    lesson: 'Potongan percakapan bisa kehilangan konteks. Minta izin sebelum membagikan pesan dan cari bantuan orang tepercaya jika perundungan berlanjut.',
    choices: [
      choice('support', 'Minta Tio berhenti meneruskan, hubungi Maya, dan tawarkan bantuan wali kelas.', 'Kamu menghubungi Maya tanpa menuntutnya menjelaskan semuanya saat itu juga. Atas persetujuannya, kalian meminta wali kelas membantu menghentikan ejekan. Tidak semua pesan bisa ditarik kembali, tetapi Maya tidak harus menghadapi situasi ini sendirian. Tio menghapus gambar dari obrolannya.', { confidence: 6, energy: -5 }, { relations: { peer: 11, friend: 4 }, flags: { supportedMaya: true } }),
      choice('publish', 'Unggah percakapan lengkap agar orang tahu konteks aslinya.', 'Sebagian teman menarik ucapannya, tetapi potongan baru kini ikut beredar. Maya berterima kasih atas niatmu sekaligus kecewa karena tidak ditanya terlebih dahulu. Membuktikan konteks benar tidak otomatis membuat seluruh percakapan aman untuk dipublikasikan.', { confidence: 2, mood: -7 }, { relations: { peer: -10 }, flags: { exposedMaya: true } }),
      choice('away', 'Bisukan grup dan tunggu sampai suasananya mereda.', 'Kamu mendapatkan jeda dari notifikasi. Sayangnya, Maya tetap menerima pesan yang menyakitkan, sementara Tio belum tahu bahwa tangkapan layar itu kehilangan konteks. Kamu masih bisa menghubunginya nanti; mengambil jeda dan memberikan dukungan tidak harus saling meniadakan.', { energy: 5, mood: -3 }, { relations: { peer: -4 } }),
    ],
  },
  {
    id: 'cheating', chapter: 1, scene: 'classroom', speaker: 'Tio', title: 'Cuma satu jawaban', milestone: true,
    text: 'Ujian tinggal sepuluh menit lagi. Tio menyelipkan secarik kertas, meminta jawaban soal terakhir. Sebelum ujian ia mengaku tidak sempat belajar karena beberapa malam harus membantu di rumah. Kamu kasihan, apalagi ia pernah menemanimu saat kamu sendiri kesulitan.\n\nGuru berkeliling di sisi lain kelas. Kamu masih perlu memeriksa pekerjaanmu. Tio menatapmu, lalu berbisik bahwa teman seharusnya saling membantu. Kamu tahu satu jawaban bisa terasa seperti bantuan kecil, tetapi nilainya nanti tidak menunjukkan materi mana yang belum ia pahami. Menolak juga bisa membuat hubungan kalian tegang. Waktu berjalan, dan kamu harus menentukan tindakanmu tanpa membuat keributan di kelas.',
    quote: 'Satu aja. Nanti gue bantuin lo kalau lagi susah.',
    lesson: 'Mendukung teman tidak harus berarti menutupi kesulitannya dengan kecurangan. Bantuan belajar atau akses dukungan bisa lebih berguna.',
    choices: [
      choice('help-later', 'Tolak memberi jawaban, lalu setelah ujian tawarkan belajar dan menemui wali kelas.', 'Tio kesal dan menjauh saat bel berbunyi. Kamu tetap menepati tawaranmu sore itu. Ia belum langsung mau bercerita, tetapi akhirnya menunjukkan soal yang membuatnya buntu. Bantuanmu tidak menyelamatkan nilai hari ini; ia membuka kesempatan untuk menghadapi ujian berikutnya dengan lebih siap.', { academic: 6, confidence: 8, energy: -4 }, { relations: { friend: 5 }, flags: { honest: true } }),
      choice('answer', 'Berikan jawaban agar ia tidak merasa ditinggalkan.', 'Tio mengucapkan terima kasih. Kamu kembali mengerjakan soal dengan gelisah, dan ia belum memahami cara mendapatkan jawaban tadi. Beberapa hari kemudian ia kembali meminta bantuan serupa untuk tugas lain. Bantuan sekali ini mulai dianggap sesuatu yang bisa diulang.', { academic: -5, confidence: -6, mood: -3 }, { relations: { friend: 3 }, flags: { cheated: true } }),
      choice('firm', 'Tolak singkat dan lanjutkan ujian; bicarakan tekanan yang ia berikan setelah kelas.', 'Kamu bisa menyelesaikan pekerjaanmu, tetapi percakapan setelah kelas terasa kaku. Kamu menjelaskan bahwa kalimat tentang teman tadi membuatmu tertekan. Tio belum setuju sepenuhnya. Setidaknya kamu sudah menyampaikan bahwa pertemanan tidak boleh dipakai sebagai syarat untuk menuruti semua permintaan.', { academic: 7, confidence: 7 }, { relations: { friend: -3 }, flags: { honest: true } }),
    ],
  },
  {
    id: 'repair', chapter: 1, scene: 'courtyard', speaker: 'close', title: 'Percakapan yang tertunda',
    text: 'Akhir kelas 11. Beberapa bulan terakhir terasa penuh ujian, pesan yang salah dimengerti, dan rencana bertemu yang batal. {close} mengajakmu duduk sebentar setelah sekolah. Kalian masih saling peduli, tetapi percakapan belakangan sering berhenti pada kata terserah.\n\nKamu juga punya hal yang ingin disampaikan: kadang kamu terlalu lelah untuk menjawab pesan panjang, bukan sedang menghindar. Di sisi lain, kamu pernah membatalkan janji tanpa penjelasan yang cukup. Kalian bisa membahas tindakan yang spesifik, berpura-pura semuanya sudah baik, atau memberi hubungan ini jarak. Tidak ada janji bahwa pembicaraan hari ini langsung nyaman. Namun, memasuki kelas 12 dengan hal yang terus dipendam juga terasa berat.',
    variants: [{ when: { boundaries: true }, text: 'Kamu mengingat kesepakatan tentang ruang pribadi. Kali ini kalian bisa mulai dari kesepakatan itu, lalu membahas bagian mana yang belum dijalankan.' }],
    quote: 'Aku nggak minta kamu selalu ada. Aku cuma pengen kita jelas satu sama lain.',
    lesson: 'Memperbaiki hubungan membutuhkan pengakuan, perubahan tindakan, dan kesediaan dua pihak. Mengambil jarak juga bisa menjadi keputusan yang sehat.',
    choices: [
      choice('talk', 'Akui bagianmu dan sepakati cara memberi kabar serta waktu untuk diri sendiri.', 'Kamu meminta maaf tanpa menambahkan alasan yang menyalahkan {close}. Ia juga mengakui pernah menuntut jawaban terlalu cepat. Kalian sepakat memberi kabar saat rencana berubah dan tidak meminta balasan setiap saat. Kepercayaan tidak langsung pulih penuh; kalian akan membangunnya lewat tindakan kecil.', { mood: 8, confidence: 7, energy: -4 }, { relations: { close: 10 }, flags: { repaired: true, boundaries: true } }),
      choice('distance', 'Jelaskan bahwa kamu membutuhkan jarak dan hentikan tuntutan hubungan untuk sekarang.', 'Pembicaraan ini sedih, tetapi jelas. Kamu tidak berjanji untuk kembali hanya agar suasana lebih mudah. Kalian sepakat tidak saling mengejar penjelasan setiap hari. Kamu memiliki ruang untuk memikirkan kebutuhanmu, sementara {close} juga bisa menentukan langkahnya sendiri.', { mood: -4, energy: 10, confidence: 8 }, { relations: { close: -4 }, flags: { bond: 'apart', boundaries: true } }),
      choice('ignore', 'Ajak bercanda dan bilang kalian tidak perlu membahas masalah lama.', 'Kalian tertawa dan pulang dengan suasana lebih ringan. Namun, belum ada jawaban tentang janji yang batal atau tekanan membalas pesan. Ketika situasi serupa terjadi lagi, kalian belum memiliki cara baru untuk menghadapinya. Kedekatan tetap ada, tetapi beberapa pertanyaan masih menggantung.', { mood: 4 }, { relations: { close: -7 }, flags: { unresolved: true } }),
    ],
  },
  {
    id: 'future', chapter: 2, scene: 'courtyard', speaker: 'close', title: 'Arah kita berbeda', milestone: true,
    text: 'Kelas 12 dimulai dengan formulir rencana setelah lulus. Ada yang ingin kuliah, mengikuti pelatihan, bekerja, atau masih mencari pilihan. Kamu mulai tertarik pada satu bidang yang cocok dengan pelajaran yang paling kamu nikmati. Jalurnya belum sepenuhnya jelas, jadi kamu ingin mencari informasi sebelum memutuskan.\n\n{close} menunjukkan rencananya. Kota dan bidang yang ia pilih berbeda dari minatmu. Ia membayangkan kalian tetap dekat kalau mengambil tujuan yang sama. Kamu juga takut kehilangan orang-orang yang membuat sekolah terasa seperti rumah. Namun, memilih arah beberapa tahun ke depan hanya untuk menghindari perpisahan terasa seperti keputusan besar yang dibuat terburu-buru.',
    variants: [{ when: { bond: 'apart' }, text: 'Meski sudah mengambil jarak, kamu dan {close} masih bisa berbicara tentang masa depan. Kali ini pertanyaannya adalah apakah kalian perlu mengikuti lingkar pertemanan yang sama setelah lulus.' }],
    quote: 'Kalau kita beda tempat, nanti masih bakal sering ngobrol nggak?',
    lesson: 'Keputusan setelah sekolah perlu mempertimbangkan minat, kemampuan, kesempatan, dan keadaanmu. Hubungan dapat dibicarakan tanpa menentukan seluruh arah hidup.',
    choices: [
      choice('own-path', 'Cari informasi sesuai minatmu dan bicarakan cara tetap terhubung meski berbeda arah.', '{close} terlihat kecewa, tetapi kamu tidak memberi janji bahwa semuanya akan tetap sama. Kalian membahas hal yang mungkin dilakukan, seperti saling berkabar tanpa menuntut jadwal identik. Kamu juga membuat daftar informasi yang masih harus dicari sebelum menentukan pilihan akhir.', { confidence: 10, academic: 5 }, { relations: { close: 3 }, flags: { ownPath: true } }),
      choice('follow', 'Ikuti tujuan {close} dulu agar kalian tidak perlu berpisah.', 'Membayangkan tetap bersama terasa melegakan. Namun, ketika membaca materi bidang itu, kamu sadar belum tahu apakah kamu benar-benar tertarik. Rencana ini belum mengikatmu selamanya, tetapi kamu perlu membedakan keinginan pribadi dari keinginan mempertahankan kedekatan.', { mood: 5, confidence: -8 }, { relations: { close: 5 }, flags: { ownPath: false } }),
      choice('counselor', 'Minta bantuan wali kelas membandingkan pilihan sebelum memberi jawaban.', 'Wali kelas tidak memilihkan jalan untukmu. Ia membantu memetakan minat, biaya, dan kesempatan yang perlu kamu cari tahu lebih lanjut. Kamu menyampaikan kepada {close} bahwa belum punya keputusan. Ketidakpastian masih ada, tetapi kini kamu punya langkah untuk memeriksanya.', { confidence: 7, academic: 5, energy: -3 }, { flags: { ownPath: true, soughtHelp: true } }),
    ],
  },
  {
    id: 'tryout', chapter: 2, scene: 'bedroom', speaker: 'Maya', title: 'Belum sampai target',
    text: 'Hasil tryout datang saat undangan acara kelas sedang ramai dibicarakan. Nilaimu belum mencapai target pribadi. Maya mengirim daftar materi yang bisa kalian ulas, sementara Tio meminta bantuan menyiapkan acara perpisahan. Kamu ingin hadir untuk semua orang dan tetap mengejar pelajaran, tetapi kalender minggu ini sudah penuh.\n\nKamu memperhatikan jam tidurmu mulai tidak teratur. Ada hari ketika kamu hanya memindahkan buku dari meja ke tas tanpa sungguh memahami isinya. Targetmu masih penting, begitu juga waktu bersama teman yang sebentar lagi akan jarang bertemu. Persoalannya bukan memilih satu selamanya. Kamu perlu menentukan apa yang realistis dilakukan minggu ini dan siapa yang perlu diberi tahu.',
    variants: [{ when: { studyHabit: true }, text: 'Kebiasaan membahas kesalahan sejak kelas 10 membantumu mengenali materi yang paling perlu diulang. Kamu tidak mulai sepenuhnya dari nol.' }],
    quote: 'Kita pilih dua bagian yang paling bikin bingung dulu. Sisanya bisa dijadwal ulang.',
    lesson: 'Target kecil yang jelas, waktu istirahat, dan pembagian tugas membantu menjaga usaha tetap bisa dijalankan.',
    choices: [
      choice('prioritize', 'Pilih materi prioritas, kurangi tugas acara, dan jaga jam istirahat.', 'Tio membagi tugas acaramu kepada teman lain setelah kamu menjelaskan kapasitasmu. Bersama Maya, kamu memeriksa alasan di balik jawaban yang salah. Kamu belum bisa menjamin hasil ujian nanti, tetapi minggu ini terasa lebih bisa dijalani daripada saat semua hal dipaksakan sekaligus.', { academic: 12, energy: 7, mood: 4 }, { relations: { peer: 5 }, flags: { prepared: true } }),
      choice('all-in', 'Ambil semua tugas dan gunakan malam untuk mengejar belajar.', 'Kamu berhasil membantu banyak orang, tetapi sesi belajar semakin larut. Beberapa pekerjaan selesai sementara materi masih terasa kabur. Teman-teman tidak tahu kamu kewalahan karena kamu terus mengatakan bisa. Mengakui batas kapasitas masih mungkin dilakukan sebelum jadwal berikutnya semakin penuh.', { academic: 3, energy: -20, mood: -9 }, { relations: { friend: 4 } }),
      choice('escape', 'Fokus pada acara dulu dan tunda memikirkan hasil tryout.', 'Hari-hari menyiapkan acara membuatmu lebih bersemangat. Kamu menikmati kebersamaan yang nyata, tetapi materi yang belum dipahami masih menunggu. Setelah acara selesai kamu akan membutuhkan jadwal pemulihan belajar; menunda tidak dengan sendirinya membuat persoalan itu lebih kecil.', { mood: 10, academic: -8, energy: -4 }, { relations: { friend: 7 } }),
    ],
  },
  {
    id: 'last-exam', chapter: 2, scene: 'classroom', speaker: 'Tio', title: 'Sebelum bel terakhir',
    text: 'Besok ujian akhir sekolah. Tio mengirim pesan bahwa ia panik dan meminta ditemani belajar. Kamu sendiri masih punya dua materi yang ingin ditinjau. Di meja ada daftar persiapan sederhana: alat tulis, jadwal, dan buku yang sudah diberi penanda. Untuk sesaat kamu teringat hari pertama kelas 10, ketika kalian bahkan belum tahu nama lengkap satu sama lain.\n\nKamu ingin menjadi teman yang bisa diandalkan, tetapi malam sebelum ujian bukan waktu untuk menyelesaikan seluruh kesulitan satu semester. Kalian bisa menetapkan waktu singkat, mencari bantuan tambahan, atau menghabiskan malam bersama. Apa pun keputusanmu, besok kamu akan menghadapi lembar ujian dengan persiapan yang sudah dibangun selama perjalanan ini.',
    variants: [{ when: { honest: true }, text: 'Tio ingat kamu pernah menolak memberi contekan, lalu tetap mau berbicara dengannya. Kali ini ia meminta bantuan memahami soal sebelum ujian dimulai.' }],
    quote: 'Gue takut blank besok. Bisa temenin sebentar?',
    lesson: 'Dukungan yang realistis punya batas. Hasil ujian dipengaruhi proses sebelumnya, bukan satu malam atau satu keputusan saja.',
    choices: [
      choice('limited', 'Sepakati 30 menit membahas satu topik, lalu selesaikan persiapan dan beristirahat.', 'Kalian membahas satu contoh soal sampai Tio bisa menjelaskan langkahnya sendiri. Setelah waktu habis kamu mengingatkan kesepakatan, lalu kembali pada persiapanmu. Tidak semua kekhawatiran menghilang, tetapi kalian menutup percakapan dengan langkah yang jelas untuk besok.', { academic: 7, energy: 5, mood: 3 }, { relations: { friend: 6 } }),
      choice('refer', 'Jelaskan kamu perlu fokus, lalu bantu hubungkan Tio dengan kelompok belajar yang masih aktif.', 'Tio sempat kecewa karena ingin ditemani kamu, tetapi akhirnya bergabung dengan kelompok kecil. Kamu menggunakan waktu untuk meninjau materi dan menyiapkan barang. Menjadi teman tidak berarti harus menjadi satu-satunya sumber bantuan setiap saat.', { academic: 9, energy: 6, confidence: 4 }, { relations: { friend: 1 } }),
      choice('overnight', 'Temani sampai larut karena kamu tidak tega meninggalkannya panik.', 'Tio merasa didampingi dan berterima kasih. Saat percakapan selesai, kamu sudah terlalu lelah untuk memeriksa materi sendiri. Besok kamu tetap berusaha, tetapi malam ini menunjukkan bahwa niat membantu dan kemampuan untuk terus membantu bukan hal yang sama.', { mood: -3, energy: -18, academic: -3 }, { relations: { friend: 8 } }),
    ],
  },
  {
    id: 'graduation', chapter: 2, scene: 'courtyard', speaker: 'close', title: 'Kita pernah di sini', milestone: true,
    text: 'Hari kelulusan. Lorong yang biasanya berisik terasa berbeda ketika tidak ada lagi kelas yang perlu dikejar. Tio mengajak foto, Maya membawa buku kecil untuk ditandatangani, dan {close} berdiri di dekat pohon tempat kalian pernah membicarakan hubungan. Hasil akademikmu sudah keluar. Ada hal yang membanggakan dan ada hal yang masih ingin kamu perbaiki.\n\nKamu tidak bisa mengulang semua percakapan selama tiga tahun ini. Namun, masih ada kesempatan menyampaikan sesuatu dengan jujur sebelum kalian membawa jadwal masing-masing. Tidak semua pertemanan harus bertahan dengan bentuk yang sama. Beberapa hubungan membaik, beberapa membutuhkan jarak, dan semuanya meninggalkan sesuatu yang kamu pelajari tentang diri sendiri.',
    quote: 'Tiga tahun ternyata cepet juga, ya. Kamu paling inget bagian yang mana?',
    lesson: 'Bertumbuh tidak berarti selalu mengambil keputusan sempurna. Kamu bisa mengakui dampak tindakanmu dan membawa pelajaran itu ke hubungan berikutnya.',
    choices: [
      choice('honest-goodbye', 'Sampaikan terima kasih dan minta maaf secara spesifik untuk hal yang belum selesai.', 'Kamu berbicara satu per satu, tanpa meminta semua orang segera memaafkan. Ada yang memelukmu, ada yang hanya mengangguk. Kamu menerima respons mereka. Kalian berfoto sebelum pulang, membawa cerita yang tidak semuanya rapi tetapi sungguh pernah kalian jalani bersama.', { confidence: 6, mood: 5 }, { relations: { friend: 4, peer: 4, close: 3 }, flags: { reflected: true } }),
      choice('stay-connected', 'Buat rencana sederhana untuk tetap berkabar tanpa janji harus selalu bersama.', 'Kalian sepakat sesekali bertukar kabar dan bertemu saat memungkinkan. Tidak ada kewajiban membalas setiap pesan secepat dulu. Kamu senang punya sesuatu untuk dinantikan, sambil mengerti bahwa rencana ini hanya bisa berjalan kalau semua orang tetap memiliki ruang untuk berubah.', { mood: 7, confidence: 3 }, { relations: { friend: 5, close: 3 }, flags: { keepContact: true } }),
      choice('quiet-goodbye', 'Tulis pesan perpisahan dan pilih pulang dengan tenang setelah berpamitan.', 'Kamu menitipkan beberapa kalimat yang lebih mudah ditulis daripada diucapkan. Setelah berpamitan, kamu berjalan keluar gerbang tanpa harus menjadi orang terakhir yang tinggal. Perpisahanmu lebih tenang, tetapi bukan berarti masa sekolah ini kurang berarti bagimu.', { energy: 5, confidence: 4, mood: 3 }, { flags: { reflected: true } }),
    ],
  },
];
